config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :users, only: [:index, :show] do
    resources :friendships, only: [:create, :update, :index, :destroy]
  end

  resources :posts, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/friendship.rb
class DupplicateValidator < ActiveModel::Validator
  def validate(record)
    friend1 = Friendship.find_by(user_id: record.user_id, friend_id: record.friend_id)
    friend2 = Friendship.find_by(friend_id: record.user_id, user_id: record.friend_id)
    record.errors[:base].push('This relationship is already created') unless friend1.nil? && friend2.nil?
  end
end

class SelfFriendshipValidator < ActiveModel::Validator
  def validate(record)
    record.errors[:base].push("You can't be friends with yourself") if record.user_id == record.friend_id
  end
end

class Friendship < ApplicationRecord
  include ActiveModel::Validations
  # validates_with DupplicateValidator, on: :create
  validates_with SelfFriendshipValidator

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user, presence: true
  validates :friend, presence: true

  def confirm_friend
    # self.update_attributes(confirmed: true)
    Friendship.create!(friend_id: user_id,
                       user_id: friend_id,
                       confirmed: true)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(friend_id: params[:user_id])
    @friendship.confirmed = false
    if @friendship.save
      flash[:notice] = 'Friend request was successfully sent.'
      redirect_to root_url
    else
      redirect_to root_url, alert: @friendship.errors.full_messages.join('. ').to_s
    end
  end

  def update
    @friendship = Friendship.find(params[:id])
    @friendship.confirmed = true

    if @friendship.save
      @friendship.confirm_friend
      redirect_to user_path(current_user.id), notice: 'Friend request was successfully confirmed.'
    else
      redirect_to user_path(current_user.id), alert: @friendship.error.full_messages.join('. ').to_s
    end
  end

  def index
    @friendships = current_user.friendships
    @inverse_friendships = current_user.inverse_friendships
  end

  def destroy
    @friendship = Friendship.find_by(friend_id: current_user.id, user_id: params[:user_id])

    if @friendship.destroy
      redirect_to user_path(current_user.id), notice: 'Friend request declined, we won\'t inform the user'
    else
      redirect_to user_path(current_user.id), alert: @friendship.errors.full_messages.join('. ').to_s
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def friend_request?(user)
    current_user.friendships.find_by(friend_id: user.id).nil?
  end

  # Users who have yet to confirme friend requests
  def pending_friends
    friendships.map { |friendship| friendship.friend unless friendship.confirmed }.compact
  end

  # Users who have requested to be friends
  def friend_requests
    inverse_friendships.map { |friendship| friendship.user unless friendship.confirmed }.compact
  end

  def confirm_friend(user)
    friendship = inverse_friendships.find { |invite| invite.user == user }
    friendship.confirmed = true
    friendship.save
  end

  def friend?(user)
    friends.include?(user)
  end
end

app/views/friendships/_confirm_decline.html.erb
<div class="request">
<p class="name">Name: <%= request.user.name %> </p>
<%= button_to 'Accept', user_friendship_path(request.user.id, request.id), method: :put, class: 'btn btn-primary' %>
<%= button_to 'Decline', user_friendship_path(request.user.id, request.id), method: :delete, class: 'btn btn-primary' %>
</div>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendships/index.html.erb
<section class="users-section">
  <ul class="users-list">
  <% @inverse_friendships.reverse.each do |request|%>
    <%=render partial: 'confirm_decline', locals: { request: request } %>
  <% end %> 
  </ul>
</section>

app/views/friendships/update.html.erb
<h1>Friendships#update</h1>
<p>Find me in app/views/friendships/update.html.erb</p>